version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  test:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Get az
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - run:
          name: Login AZ
          command: |
            az login --service-principal --username ${ARM_CLIENT_ID} --password ${ARM_CLIENT_SECRET} --tenant ${ARM_TENANT_ID}
            az account set --subscription ${ARM_SUBSCRIPTION_ID}
            az configure --defaults group=${ARM_RES_GROUP_NAME}
      - run:
          name: Get Terraform
          command: |
            wget https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_linux_amd64.zip
            unzip terraform*.zip
            sudo mv terraform /usr/local/bin
      - run:
          name: Run Go AWS tests
          command: |
            export PREFIX="$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 5 | head -n 1 | sed -E 's/^([0-9]+)(.*)/\2\1/g')"
            echo "PREFIX=${PREFIX}"
            cd tests
            make aws
            cd ..
          environment:
            - TF_STATE_REGION: us-east-1
      - run:
          name: Run Go GCP tests
          command: |
            echo -n "${GOOGLE_APPLICATION_CREDENTIALS_CONTENT}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
            export PREFIX="$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 5 | head -n 1 | sed -E 's/^([0-9]+)(.*)/\2\1/g')"
            echo "PREFIX=${PREFIX}"
            cd tests
            make gcp
            cd ..
      - run:
          name: Run Go Azure tests
          command: |
            export PREFIX="$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 5 | head -n 1 | sed -E 's/^([0-9]+)(.*)/\2\1/g')"
            echo "PREFIX=${PREFIX}"
            cd tests
            make azure
            cd ..
      - slack/status:
          fail_only: true

  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build image
          command: docker build -f docker/Dockerfile . -t ${dockerhub_repo}
      - run:
          name: Login into DockerHub
          command: echo ${dockerhub_token} | docker login -u ${dockerhub_user} --password-stdin
      - run:
          name: Push image
          command: docker push ${dockerhub_repo}:latest
      - slack/status:
          fail_only: true

workflows:
  version: 2
  build_and_test:
    jobs:
      - approve_test:
          type: approval
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - approve_test
      - approve_build:
          type: approval
          requires:
            - test
      - build:
          requires:
            - approve_build
