version: "3"

services:

  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    restart: "always"
    networks:
      - prometheus
    volumes:
      - prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    restart: "always"
    networks:
      - prometheus
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    ports:
      - 3000:3000

networks:
  prometheus:
    driver: bridge

volumes:
  prometheus:
  grafana:
